### ISSUE TITLE
New releases

### ISSUE THREAD

**Issue by ghost** [dmbaturin/soupault#11]
I you visit here:

https://github.com/dmbaturin/soupault/releases

Most recent build is 1.4, however here:

https://files.baturin.org/software/soupault

you also find 1.5, 1.6 and 1.7. I think the newer releases should be added to
GitHub, or alternatively this other page should be linked in a prominent
location.

**Comment by dmbaturin** [comment]
I agree, it's a good point. I should add the files here as an alternative location.

**Comment by dmbaturin** [comment]
Releases are mirrored here again.
