### ISSUE TITLE
Wrond date in blog post

### ISSUE THREAD

**Issue by ngirard** [dmbaturin/soupault#17]
Hey, congrats for this v2.0 release, and thanks for your work & dedication !

You might want to change the date in the accompanying blog post from `2020-09-20` to `2020-10-20`.

Cheers !

**Comment by dmbaturin** [comment]
The date isn't wrong—that post was posted on September the 20th. I just didn't put the binaries on Github until now—the main location is https://files.baturin.org/software/soupault/

I decided to mirror the binaries here again for those who prefer CDNed links in their CI scripts.

**Comment by dmbaturin** [comment]
Hhm. I suppose I missed the fact that people may use Github as a release notification mechanism! I'll keep posting new releases here in sync with their announce on the blog from now on then.

**Comment by ngirard** [comment]
Fair enough. 
I'll soon be using an rss reader again for that purpose -- adding your blog as a feed. [NewsFeed](https://gitlab.com/news-flash/news_flash_gtk) seems nice, i'm just reluctant to use Flatpack on my system.
Sorry for the noise !
