### ISSUE TITLE
The extensions check should look at the second-to-last extension

### ISSUE THREAD

**Issue by aantron** [dmbaturin/soupault#22]
...or some variant scheme. So, a draft file should be `foo.draft.md`, not `foo.md.draft`. This helps editors detect the language of the file.

At the moment, `ignore_extensions` doesn't seem to allow this even with workaround:

```
ignore_extensions = ["draft.md"]
```

as it appears to (tested, but did not read code) to compare only the last extension (`.md`) against `ignored_extensions`.

Of course, using this workaround only wouldn't scale well to having sources in multiple languages.

I suggest searching through all the extensions for matches with `ignore_extensions`, or searching up to the last two.

**Comment by dmbaturin** [comment]
Fair point! Let me make a fix.

**Comment by dmbaturin** [comment]
Could you re-test with this fix?

**Comment by aantron** [comment]
Thanks, it works!
