### ISSUE TITLE
Allow not to insert newline when parsing/outputing HTML

### ISSUE THREAD

**Issue by lthms** [dmbaturin/soupault#25]
I am currently trying to rewrite my plugin to mark external url, in order to use SVG icons in place of dedicated fonts. My issue is, when I do something like

```lua
icon = HTML.parse('<svg class="icon"><use xlink:href="/~lthms/imgs/icons.svg#github"></use></svg>')
HTML.append_child(link, icon)
```

The produced HTML “pretty-print” the `svg` tag… which introduces newline in my `a` tag… which introduces unwanted whitespace.

Is there a way to tell `soupault` not to do that? Otherwise, we could imagine `append_child_inline` in addition to `append_child` (and alike)

**Comment by dmbaturin** [comment]
This issue seems to happen at the printing rather than the insertion stage.

```
utop # #require "lambdasoup";;

utop # open Soup.Infix;;
utop # let svg_src = "<svg class=\"icon\"><use xlink:href=\"/~lthms/imgs/icons.svg#github\"></use></svg>" ;;
utop # let doc = Soup.parse "<p> <a>foo</a> </p>" ;;
utop # Soup.append_child (doc $ "a") (Soup.parse svg_src) ;;
utop # Soup.pretty_print doc ;;
- : string =
"<p>\n <a>foo\n <svg class=\"icon\">\n  <use href=\"/~lthms/imgs/icons.svg#github\"></use>\n </svg>\n</a>\n</p>\n"

utop # Soup.to_string doc ;;
- : string =
"<p> <a>foo<svg class=\"icon\"><use href=\"/~lthms/imgs/icons.svg#github\"></use></svg></a> </p>"
```

I've added a new option for whitespace control:

```toml
[settings]
  pretty_print_html = false
```

It forces soupault to use `Soup.to_string` rather than `Soup.pretty_print` for rendering output files. That function doesn't intentionally remove any whitespace, it just refrains from inserting any on its own, so it may be a good solution.

Let me know if it helps.

**Comment by lthms** [comment]
It works perfectly, thanks!

**Comment by aantron** [comment]
This is arguably an upstream bug. Lambda Soup's (that is, Markup's) pretty-printer is supposedly sensitive to the meaning of elements, and should only insert whitespace where it would have no semantic effect (typically, where there is already whitespace around HTML phrasing content, and anywhere around HTML flow content). It should probably just treat all SVG (and MathML) as opaque, while IIRC it currently applies blind pretty-printing to it instead.

**Comment by aantron** [comment]
I opened https://github.com/aantron/markup.ml/issues/63 to track it in Markup. Given this is already resolved and released in Soupault, I'm not going to rush doing it, but it might help someone else in the future not to have this questionable behavior on Markup's part.
