### ISSUE TITLE
HTML.inner_html should not insert any whitespace that wasn't there

### ISSUE THREAD

**Issue by dmbaturin** [dmbaturin/soupault#26]
`HTML.inner_html` pretty-prints HTML, that is, inserts additional whitespace that wasn't there. This may cause issues, and also just different from what the browser equivalent does.

My idea is to:

1. Switch `HTML.inner_html` to use `Soup.to_string` and preserve original whitespace untouched.
2. Add a way to prettify it, e.g. `HTML.inner_html_pretty`, or an optional argument: `HTML.inner_html(elem, 1). 

CC @lthms

**Comment by dmbaturin** [comment]
@lthms I can't reproduce the issue. Do you have a procedure to trigger it? From my test it preserves original whitespace, or lack thereof.

```
[dmbaturin@careless wtest]$ cat plugins/test.lua 
elem = HTML.select_one(page, "body")

h = HTML.inner_html(elem)

Log.debug(h)
[dmbaturin@careless wtest]$ cat site/index.html 
<h1>Welcome!</h1><p>Welcome to my homepage. It's under construction.</p><p>Very incomplete!</p>
[dmbaturin@careless wtest]$ ~/devel/soupault/_build/default/src/soupault.exe --debug
[DEBUG] Loading configuration from [widgets.generator-meta]
[DEBUG] Loading configuration from [widgets.no-blink]
[DEBUG] Loading configuration from [widgets.page-title]
[DEBUG] Loading configuration from [widgets.test]
[DEBUG] Widget test is loaded from plugin file plugins/test.lua
[DEBUG] Widget processing order: generator-meta test no-blink page-title
[INFO] Processing page site/index.html
[INFO] Using the default template for page site/index.html
[INFO] Processing widget generator-meta on page site/index.html
[INFO] Processing widget test on page site/index.html
[DEBUG] 
    
  

<h1>Welcome!</h1><p>Welcome to my homepage. It's under construction.</p><p>Very incomplete!</p>

[INFO] Processing widget no-blink on page site/index.html
[DEBUG] Page has no elements matching selector "blink", nothing to delete
[INFO] Processing widget page-title on page site/index.html

```

**Comment by lthms** [comment]
I am confused, you are right, the issue was on my side. It turns out Emacs was adding unwanted spaces, not `soupault`… Sorry about the misreport (and thank you for providing `String.trim`, which solves my issue)

**Comment by dmbaturin** [comment]
I believe `String.trim` is the second string function any standard library should provide, right after `String.length`.
