### ISSUE TITLE
Make site_index available in all pages, not just index pages

### ISSUE THREAD

**Issue by jchavarri** [dmbaturin/soupault#28]
Thanks for building Soupault, it has a very interesting design :) I am exploring it as a way to build the docs site for [melange](https://github.com/melange-re/melange) and having a lot of fun working with it as it allows to iterate quickly and it's very flexible.

I am trying to build a side nav bar for this experiment. For that, I created a plugin that reads from `site_index` and then creates a template and injects some values from this global, but I noticed `site_index` is empty in most pages except the index ones. I was expecting it to be available in all pages.

I saw this commit where the index stopped being created for all pages: https://github.com/dmbaturin/soupault/commit/dabb437569afca11192045ce63e8e89d8e537bdf but I don't understand well the reason.

Is there a way to do this kind of nav bar content auto-generation from index? I guess I could dump the index.json and read from there, but I am not familiar with Lua and it seems more straightforward to use `site_index` directly.

Edit: hm, I guess I could read `index.json` with `Sys.read_file(config["index_file"])`, but then I'd need to run Soupault twice after adding a new page, to make sure everything is updated: first time to update json file, second time to make sure the plugin gets latest data to generate the nav bar html.

**Comment by dmbaturin** [comment]
Making index data available to every page runs into a chicken and egg problem.

I made that compromise for two reasons.

First, it is to make the complete site index available to every index page (for example, make two different views of the same sections, or simply include all subsections).

Second, it is to make the workflow parallelizable in anticipation of the multicore OCaml getting merged.

Now soupault creates a flat list of page paths from the site directory tree, then separates it into "content" and "index" page lists. Then it processes the content pages and extracts index data from them, and then processes index pages .

The current recommended solution is a TeX-like workflow: first run 'soupault --index-only' to generate index.json, then make it into HTML in a second pass.

It may be possible to make the two-pass workflow a built-in feature. However, it will require keeping all pages in memory for the entire build duration, which may cause issues for very large sites and small build hosts. For this reason I think it should be optional.

If you have ideas regarding the design and implementation of this feature, please share.

**Comment by jchavarri** [comment]
I see, makes sense, thanks for explaining! I had some intuition of the problem but the explanation makes it very clear.

Re: parallelization and make the two-pass a built-in feature. I wonder if leveraging dune would help towards these purposes. If Soupault somehow converted all the actions in a building process into custom Dune rules, then it could get for free:
- parallelization
- incremental builds, as dune keeps hashes of input files and doesn't re-run rules if it's not needed

With these two improvements, maybe it'd become cheap enough to run the build process twice, as all intermediate steps would be skipped.

I am closing the issue now, as there's the workaround with json file. Thanks again!
