### ISSUE TITLE
Make index entry sorting method configurable

### ISSUE THREAD

**Issue by dmbaturin** [dmbaturin/soupault#30]
As of now, soupault assumes that the field to `sort_by` is some kind of date. This is _usually_ correct, since most of the time index generators are used for blogs, but it's not always the case.

When it's not a date, there are two problems with the current behaviour:
* Trying to parse it as a date has a performance impact.
* The only fallback option is lexicographic sort.

We may want to make it configurable, e.g. like this:

```toml
[index]
  sort_by = "field_name"
  sort_type = <"calendar" | "lexicographic" | "numeric" >
```

CC @jchavarri

**Comment by jchavarri** [comment]
This sounds great. I am not sure `numeric` would be even needed, as I can't think of any case that can't be covered with `lexicographic`. But maybe there are?

Another suggestion is to model the config as a tuple in a single field, to avoid situations where a config has `sort_type` being defined without `sort_by`.

So, something like:

```
[index]
  sort_by = ["field_name", <"calendar" | "lexicographic" | "numeric" >]
```

but then this would introduce the issue of array length validatione, and it removes the possibility of having default value in `sort_type`, so I am not sure it's a good idea.

**Comment by dmbaturin** [comment]
Lexicographic comparison is usually designed so that say `"ab" < "b"` (because it starts with an "a"), which has a nasty side effect on numeric values: `"19" < "9"`. So it's relevant for your case if you want to sort more than ten pages.

**Comment by jchavarri** [comment]
Ah right, I generally work around that with leading zeroes 😅 but I see how having `numeric` option would be more user friendly.

**Comment by dmbaturin** [comment]
I gave the implementation cursory testing, but I'd like to hear from you before including it in an official release, since you have a case for it.

```toml
[index]
  sort_type = "numeric"
```

**Comment by jchavarri** [comment]
Looks great, thanks! In case it's interesting, I added it in https://github.com/jchavarri/melange-docs/commit/23d683eff257d3d09a444339a5c45d3757c2479a.

One minor thing I noticed is that I changed the configuration of `sort_type` to `numeric`, but left the dates values that I had, and I called `soupault`, but no errors were shown. At this point, I was unsure what ordering would apply (it seems there was some kind of ordering but I could not figure out which one exactly). I wonder if `numeric` should be more strict?

**Comment by dmbaturin** [comment]
Right now soupault assumes that any valid value (i.e. one that could be parsed) is greater than any invalid value. Two invalid values are compared lexicographically.

I've done a small survey of other projects.

* Jekyll: ignores all files in `_posts` that aren't named `YYYY-MM-DD-post-title.md`, so the issue is not applicable.
* Hugo: ignores all date parse errors, assumes invalid dates are older than any valid ones. Very similar to soupault.
* Zola: panics on invalid dates.
```
Building site...
thread 'main' panicked at 'error deserialising page: Error { kind: Msg("Error when parsing front matter of page `/home/dmbaturin/tmp/zola-test/myblog/content/blog/third.md`"), source: Some(Error { kind: Toml(Error { inner: ErrorInner { kind: Custom, line: Some(0), col: 0, at: Some(0), message: "data did not match any variant of untagged enum MaybeDatetime", key: ["date"] } }), source: None }) }', components/site/src/lib.rs:264:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I agree that a wish to prevent invalid sort keys is a valid one. However, I'm not sure if it should be the default. I think I'll add the following optional parameter for now:

```toml
[index]
  sort_type = "numeric"
  strict_sort = true
```

**Comment by dmbaturin** [comment]
Well, failing on errors wasn't hard, reporting them in a meaningful way was. ;)

Now it will produce different errors for _malformed_ and _missing_ sorting key fields and dump a JSON-encoded entry to make it easier to find the bad page:

For malformed field:

```
[DEBUG] Field value "2018--08-06" could not be parsed as a date, interpreting as a string
[ERROR] Cannot sort entries using sort_by="date": value "2018--08-06" could not be parsed as a date. The offending entry is:
{
  "url": "/misc/blank-page",
  "page_file": "site/misc/blank-page.inc",
  "nav_path": [
    "misc"
  ],
  "title": null,
  "tags": null,
  "images": null,
  "excerpt": "This page is intentionally left blank",
  "date": "2018--08-06",
  "category": "Misc"
}

```

For a missing field:

```
[ERROR] Cannot sort entries using sort_by="date", the following entry is missing that field:
{
  "url": "/misc/blank-page",
  "page_file": "site/misc/blank-page.inc",
  "nav_path": [
    "misc"
  ],
  "title": null,
  "tags": null,
  "images": null,
  "excerpt": "This page is intentionally left blank",
  "date": null,
  "category": "Misc"
}

```

**Comment by dmbaturin** [comment]
I'm closing this since it seems to work as expected. If any issues appear, feel free to reopen.
