### ISSUE TITLE
Setting include_subsections on an index view scoped to a section gets the wrong entries

### ISSUE THREAD

**Issue by ryanartecona** [dmbaturin/soupault#35]
Hi! I really like the general design you've chosen for soupault, and I'm working on reviving a neglected blog and moving it to soupault.

I've hit a snag trying to set up indexes the way I want them, and I've reduced the problem to something small and reproducible.

Given a soupault.conf:
```toml
[settings]
  debug = true

[index]
  index = true
  sort_by = "url"

[index.views.blog]
  section = ["blog"]
  include_subsections = true
  index_selector = "#blog-index"
```

And a site structure like this:
```
> tree site
site
├── about.html
├── blog
│   ├── foo.html
│   ├── index.html
│   └── subsection
│       └── post-1.html
└── index.html
```

(with a `<div id="blog-index"></div>` inside `site/index.html`)

I get index data on that blog view like this:
```json
[
  {
    "url": "/blog/foo",
    "page_file": "site/blog/foo.html",
    "nav_path": [
      "blog"
    ]
  },
  {
    "url": "/about",
    "page_file": "site/about.html",
    "nav_path": []
  }
]
```

So I think that index view with `section = ["blog"]` together with `include_subsections = true` is getting me pages in site/blog/ as well as posts in _parent_ directories, instead of subdirectories. If I remove the `include_subsections` setting, things work as expected.

I'm not super familiar with this codebase, but after browsing the code trying to figure out what was happening, it looks like the places `Path_options.page_included` calls out to `Path_options.section_matches` have the page file and the index entry file swapped in the call site, i.e. when `section_matches` compares them for equality only (`include_subsections = false`) then it still works, but when it does a subdirectory test (`include_subsections = true`) it's testing if the index entry file is a subdirectory of the section path instead of vice versa.

**Comment by dmbaturin** [comment]
Thanks for pointing this out! Looks like I haven't tested `include_subsections` nearly as much as I should.

It looks like `FilePath.is_subdir` doesn't handle single-dir paths correctly as of fileutils 0.6.3.

```
(* this works *)
utop # FilePath.is_subdir "site/misc/foo" "site/misc" ;;
- : bool = true

(*This doesn't *)
utop # FilePath.is_subdir "site" "site/misc" ;;
- : bool = false
 
(* This doesn't work either *)
utop # FilePath.is_subdir "site/misc" "site" ;;
- : bool = true
```
I've replaced it with a hack using `FilePath.is_updir`, which works better. Just pushed a commit that fixes _spurious_ page issue for me. Latest code should be able to build your website correctly.

There's also an issue with pages in sub-sub-sections not being included, but that issue seems to be of a different nature and needs further investigation.

Do you have a setup for building from source, or will you need prebuilt binaries to test my fix? If you need prebuilt binaries, which OS are you using?

**Comment by ryanartecona** [comment]
I haven't yet built from source. I could try, but if you can share a macOS binary that would certainly be faster for me.

I could be missing something, and I don't have a console handy to poke myself, but your FilePath examples...make sense to me? I mean those `is_subdir` checks look like what I would expect them to be. I'm assuming the first arg is supposed to be the subdir, and the second arg the parent/ancestor dir.

**Comment by dmbaturin** [comment]
> I'm assuming the first arg is supposed to be the subdir, and the second arg the parent/ancestor dir.

No, the first argument is the [parent dir](https://docs.ocaml.pro/html/LIBRARY.fileutils@fileutils.0.6.3/FilePath/index.html#val-is_subdir). Notice that `FilePath.is_subdir "site/misc/foo" "site/misc"` evaluates to `true`, which is correct, but when a path consists of only one directory, the relationship is reversed.

>a macOS binary that would certainly be faster for me

The CI for this repo is set to run on macOS, mostly because I don't have any Apple hardware anymore so I use it as a way to produce macOS binaries for releases. Here's the artifact for the commit in question: https://github.com/dmbaturin/soupault/suites/2955181315/artifacts/66513266

**Comment by dmbaturin** [comment]
>Notice that `FilePath.is_subdir "site/misc/foo" "site/misc"` evaluates to `true`, which is correct

Wait, sorry, looks like I need some sleep. It's not correct according to the docs logic, it's reversed! Seems you are right, the real argument order is the opposite of what the docs say.

Swapping the arguments seems to fix the issue, and also fix missing sub-sub-sections. Here's the build: https://github.com/dmbaturin/soupault/actions/runs/923631319

**Comment by ryanartecona** [comment]
Aha! I guess it's good that I didn't go read those docs, or I would've convinced myself the problem was elsewhere too.

I've downloaded the executable from the latest master build, but on first run I get this error (same soupault.conf as the issue description):
```
> ./soupault.exe 
Fatal error: exception Dune__exe__Otoml.Key_error("Failed to retrieve a value at date_formats: cannot retrieve field \"date_formats\": field \"date_formats\" not found")
```

Adding a `date_formats = ["%F"]` to my `[index]` section gets me a second config error:
```
[WARNING] Index view "blog" does not have index_item_template, index_template, or index_processor option, using default template
Fatal error: exception Dune__exe__Otoml.Key_error("Failed to retrieve a value at extract_after_widgets: cannot retrieve field \"extract_after_widgets\": field \"extract_after_widgets\" not found")
```

And finally adding `extract_after_widgets = []` to the `[index]` section gets me a working run that seems to get the correct index entries now:
```json
[
  {
    "url": "/blog/subsection/post-1",
    "page_file": "site/blog/subsection/post-1.html",
    "nav_path": [
      "blog",
      "subsection"
    ]
  },
  {
    "url": "/blog/foo",
    "page_file": "site/blog/foo.html",
    "nav_path": [
      "blog"
    ]
  }
]
```

I also did some extra tinkering with more deeply nested subsections and different `sections`/`include_subsections` combinations, and they all seem to work as intended now. Thanks!

**Comment by dmbaturin** [comment]
Thanks for catching the unhandled exceptions! It's coming from my work on a new library for TOML handling that will replace to.ml.

It still has rough edges and functions have different behaviour. I fixed most of them earlier, but some escaped me as your testing shows, I'll fix them too.

**Comment by dmbaturin** [comment]
I think 3e138b789f94767aa fixes the last issues with missing options causing exceptions instead of being properly substituted with defaults.

**Comment by ryanartecona** [comment]
Yup! Just confirmed commit fixed the errors I saw.

**Comment by dmbaturin** [comment]
Cool, thanks for testing!

I'm working on a few additions for the next release. My plan is to rework the config handling code to make the _effective_ config (i.e. with all defaults) available to Lua plugins (and for viewing with `--show-effective-config`). I think it will take about a week, then I'll make a 2.8.0 release.

If you think a maintenance release is warranted, e.g. for CI purposes, I think I can arrange a release with just this fix. Let me know what you think.

**Comment by ryanartecona** [comment]
Sure thing! Thanks for being responsive.

I don't personally need a maintenance release for this, so I'm all set.

**Comment by dmbaturin** [comment]
Ok, I'll close the issue then.
