### ISSUE TITLE
Rename or support `soupault.toml`

### ISSUE THREAD

**Issue by toastal** [dmbaturin/soupault#37]
having 

```toml
# vim: filetype=toml
```

at the top of my configuration file seems silly. If it's a TOML file, why not make it `soupault.toml` so syntax highlighters and other things can understand this? Unless, like, you're gonna autoparse multiple formats from the `.conf` (:crossed_fingers: Dhall).

**Comment by dmbaturin** [comment]
Damn, you are just a day late for the 2.8.0 release. It would be a simple change, I just never thought about it (most configs are not named after their format, even if they can benefit from it).

I'll add it in the next release then.

**Comment by dmbaturin** [comment]
I think the plan should be:

* Change the config loader to look for `soupault.toml`, or if it doesn't exist, for `soupault.conf`.
* Output a debug-level message to say which file configuration is being loaded from.
* Add a warning message if both files exist in the same dir (i.e. `[WARNING] Both soupault.toml and soupault.conf exist in the directory, using soupault.toml`

**Comment by toastal** [comment]
Yeah, it seems to make people angry in the JS world now with all these RC files not having prefixes. Still keeping my fingers crossed for Dhall on OCaml :P

**Comment by dmbaturin** [comment]
>Still keeping my fingers crossed for Dhall on OCaml

Maybe we should make an implementation in Coq that can be extracted to both OCaml and Haskell...

So far I'm writing on a rather more humble goal: a decent TOML library with flexible formatting and human-friendly error reporting. The `--show-effective-config` is using its first chunk. For a humble-looking goal it turned out surprisingly effort-intensive because the full TOML spec is neither minimal or very obvious. ;)

**Comment by toastal** [comment]
Yeah, but I love having types and terminating functions in my configurations. I think the GSoC project is to get the Dhall->TOML converter so ¯\_(ツ)_/¯

**Comment by dmbaturin** [comment]
Oh, I mean a Dhall implementation in Coq. That would make quite an ICFP paper.

Anyway, if you find any problems with my implementation, feel free to reopen the issue. I'll close it for now.
