### ISSUE TITLE
section and exluded_section backwards

### ISSUE THREAD

**Issue by sgpthomas** [dmbaturin/soupault#5]
If I am understanding the documentation correctly, it seems like `section` and `exclude_section` are doing the opposite of what they are supposed to do. `section` should only apply a widget to a subdirectory in `site` but it applies the widget to everything except that directory. `exclude_section` does the reverse.

**Comment by dmbaturin** [comment]
Indeed, there's an issue with that. The root cause is odd behaviour of `FilePath.is_subdir`:

```
# FilePath.is_subdir "foo/bar" "foo" ;;
- : bool = true

# FilePath.is_subdir "foo/bar" "foo/" ;;
- : bool = false

```

I've pushed a workaround, please test.

**Comment by sgpthomas** [comment]
Seems to work as expected. I'll let you close the issue.

**Comment by dmbaturin** [comment]
Forgot to close. ;)
If similar issues re-appear, feel free to reopen.
