### ISSUE TITLE
default index processor broken

### ISSUE THREAD

**Issue by sgpthomas** [dmbaturin/soupault#8]
It looks like the default index processor detects the proper elements in the blog because I turned on debug and I could see the correct json being displayed. However, it doesn't seem to copy the elements over correctly. It  correctly use the `index_item_template` to create an element for the blog but it doesn't copy any elements into it.

I was able to get index generation working fine with a custom index generator.

**Comment by dmbaturin** [comment]
Frankly, I thought no one is using the `index_item_template` option, so I though it's safe to make a breaking change there.

The breaking change is that it's now a mustache template. Here's the blog setup of soupault.neocities.org for example:

```
[index]
  index = true
  index_selector = "#blog-index"

  index_title_selector = "h1#post-title"
  index_date_selector = ["time#post-date", "time"]
  index_excerpt_selector = ["p#post-excerpt", "p"]

  newest_entries_first = true

  extract_after_widgets = ["insert-reading-time"]

  index_item_template = """
<h2><a href="{{url}}">{{title}}</a></h2>
<p><strong>Last update:</strong> {{date}}.</p>
<p><strong>Reading time:</strong> {{reading_time}}.</p>
<p>{{{excerpt}}}</p>
<a href="{{url}}">Read more</a>
"""

strip_tags = false

[index.custom_fields]
  reading_time = { selector = "span#reading-time" }
```

This is much more flexible than being able to insert only a single field in that "template", and allows to avoid external script in all but really complicated setups, so I think the breaking change was worth it.

**Comment by sgpthomas** [comment]
yeah that seems like a good change. I think I'll probably stick with a custom indexer though
